from flask import Flask, request, jsonify, render_template
import spacy
import random
import gspread
sa = gspread.service_account()
sh = sa.open("team32")
wks = sh.worksheet("team_data")

app = Flask(_name_)

nlp = spacy.load("en_core_web_sm")

# data training

greetings = ["hello","hi","hey","good morning","good afternoon","good evening","mornin"]
goodbyes = ["bye","goodbye","see you","take care"]
purposes = ["what can you do?", "what is your purpose?","how can you help me?","help","tell me about yourself","what can you do", "how are you?"]
risk_appetites = ["what do you mean by risk appetite?","what is risk appetite?","risk appetite?","risk appetite"]
menus = ["open menu","display menu","menu","i want to invest","i want to know about investments","how do i invest","help me"]
financialphrases = ['yield', 'credit card debt', 'bond', 'real estate investing', 'credit rating', 'financial goals', 'market trend', 'equity', 'active investing', 'bankruptcy', '529 plan', 'commodity trading', 'certificate of deposit (CD)', 'passive income', 'stock exchange', 'capital market', 'technical analysis', 'portfolio rebalancing', 'business loans', 'mutual fund', 'retirement planning', 'joint brokerage account', 'financial independence', 'tax planning', 'cryptocurrency', 'venture capital', 'investment portfolio', 'options', 'market volatility', 'inflation', 'taxes', 'financial advisor', 'passive investing', 'socially responsible investing', 'interest rate', 'dividend', 'wealth management', 'retirement savings', 'liquidity', 'fundamental analysis', 'bear market', '401(k) rollover', 'individual brokerage account', 'initial public offering (IPO)', 'net worth', 'cash flow', 'financial literacy', 'hedge fund', 'early retirement', 'market capitalization', 'capital loss', '401(k)', 'dollar-cost averaging', 'stock options', 'stock market', 'blue chip', 'mortgage', 'risk management', 'forex trading', 'accounting', 'asset allocation', 'student loans', 'dividend reinvestment plan (DRIP)', '529 college savings plan', 'money market account', 'savings', 'diversification', 'term life insurance', 'robo-advisor', 'venture debt', 'whole life insurance', 'diversified portfolio', '529 prepaid tuition plan', 'annuity', 'risk tolerance', 'credit score', 'IRA', 'market correction', 'health savings account (HSA)', 'estate planning', 'capital gains', 'rental property investing', 'capital preservation', 'emergency fund', 'angel investing']

datas = []
data_list = []

# data processing

def is_greeting(text):
    return any(greeting in text.lower() for greeting in greetings)

def is_goodbye(text):
    return any(goodbye in text.lower() for goodbye in goodbyes)

def is_purpose(text):
    return any(purpose in text.lower() for purpose in purposes)

def is_riskappetite(text):
    return any(riskappetite in text.lower() for riskappetite in risk_appetites)

def is_menu(text):
    return any(menu in text.lower() for menu in menus)

def is_financialphrase(text):
    return any(financialphrase in text.lower() for financialphrase in financialphrases)




# data display

def chatbot_response(message):
    global datas
    global data_list
    doc = nlp(message)
    if is_greeting(message):
        response = "Hello, I'm your financial assistant. How can I help you today?"
    elif is_goodbye(message):
        response = "Goodbye! Have a nice day!"
    elif is_purpose(message):
        response = f"I'm your personal financial assistant.<br>I can help in a variety of ways but I excel at recommending schemes.<br>Tell me more about yourself and we can get started with that! <br><br>Enter your email to log-in or sign-up."
    elif is_riskappetite(message):
        response = "Risk appetite is the level of risk that an organization is willing to accept while pursuing its objectives, and before any action is determined to be necessary in order to reduce the risk."
    elif is_financialphrase(message):
        response = "currently we only support insurance, savings & investments but we're continually adding more. type 'menu' to access."

   
    elif message.endswith(" years"):
        datas.append(message.replace(" years", "").strip())
        response = "please input liquidity preference: " + f"<br>( liquid, illiquid or partially liquid )<br>"

    elif message.endswith("@gmail.com"):
        global row_number
        global index
        email = message.replace("email:", "").strip()
        existing_user = False
        row_number = None
        column_e_values = wks.col_values(5)  # Get all values in column E
        for index, value in enumerate(column_e_values, start=1):
            if value == email:
                existing_user = True
                row_number = index  # Adding 1 to account for header row
                datas = wks.row_values(row_number)[0:4]
                response = "Welcome back! Your details: "
                response += f"Duration: {datas[0]}, Liquidity: {datas[1]}, Capital: {datas[2]}, Income: {datas[3]}" 
            
                break
        if not existing_user:
            empty_row = len(wks.get_all_values()) + 1
            wks.update(f"E{empty_row}", email)
            row_number = index+1
            response = "Thank you for registering! Your details have been added to the database. type 'menu' to begin. "



    # Wait for user response and store in datas list
    elif len(datas) == 1:
        datas.append(message.strip())
        response = "please input capital: "
    elif len(datas) == 2:
        datas.append(message.strip())
        response = "please input your income: "
    elif len(datas) == 3:
        datas.append(message.strip())
        response = f"Thank you for providing your information! type 'recommend' to view your recommended schemes.<br> This may take a few seconds...please wait while we process your request"
        data_list = [datas]
        wks.update(f'A{row_number}:D{row_number}', data_list)
        print(data_list)





    elif is_menu(message):
        response = f"Please type 'i' for insurance<br> or 's' for savings & investments"
    elif message.lower()=="":
         response = "it seems that you haven't entered a message."   
   
    elif message.lower()=="i":
        response = """
        INSURANCE IS A WAY TO PROTECT AGAINST POTENTIAL LOSSES BY TRANSFERRING THE RISK TO AN INSURANCE COMPANY IN EXCHANGE FOR A PREMIUM. IF A COVERED EVENT OCCURS, THE INSURANCE COMPANY PAYS OUT COMPENSATION TO THE POLICYHOLDER. THE PURPOSE OF INSURANCE IS TO PROVIDE FINANCIAL PROTECTION AND PEACE OF MIND.
        (please type "general" for general insurance or "life" for life insurance.)
        """
    elif message.lower() == "general":
        response = "You selected General Insurance. Please type 'health' for Health Insurance, 'motor' for Motor Insurance, 'travel' for Travel Insurance, 'property' for Property Insurance."
    elif message.lower() == "life":

        response = "You selected Life Insurance. please type 'a' for term insurance, 'b' for health specific insurance, 'c' for unit linked plan, 'd' for Non linked plan, 'e' for pension/ annuity."
    elif message.lower() == "health":
        response = """ HEALTH INSURANCE
HEALTH INSURANCE IS A TYPE OF INSURANCE THAT COVERS THE COST OF MEDICAL EXPENSES INCURRED BY AN INDIVIDUAL OR GROUP. IN EXCHANGE FOR PAYING A PREMIUM, THE INSURER AGREES TO PAY FOR CERTAIN HEALTHCARE SERVICES SUCH AS DOCTOR VISITS, HOSPITAL STAYS, AND PRESCRIPTION DRUGS. THE COVERAGE AND COST OF THE PREMIUM CAN VARY BASED ON THE PLAN CHOSEN AND THE INDIVIDUAL'S HEALTH STATUS. HEALTH INSURANCE IS AN IMPORTANT FINANCIAL TOOL THAT CAN HELP PROTECT AGAINST UNEXPECTED MEDICAL EXPENSES AND ENSURE ACCESS TO NECESSARY HEALTHCARE SERVICES.
DURATION: 
[3 MONTHS TO 3 YEARS]
PAYMENT PLAN:
MONTHLY/ ANNUAL/ ONE TIME
PAYOUT:
REIMBURSEMENT OF HEALTH COST IN ACCORDANCE WITH SCHEME SPECIFICATIONS
"""
    elif message.lower() == "motor":
        response = """MOTOR INSURANCE
VEHICLE INSURANCE IS A TYPE OF INSURANCE THAT PROVIDES FINANCIAL PROTECTION TO DRIVERS IN THE EVENT OF AN ACCIDENT, THEFT, OR DAMAGE TO THEIR VEHICLE. IN EXCHANGE FOR PAYING A PREMIUM, THE INSURER AGREES TO PAY FOR CERTAIN COSTS ASSOCIATED WITH THESE EVENTS, SUCH AS REPAIRS, MEDICAL EXPENSES, AND LIABILITY CLAIMS. THE AMOUNT OF COVERAGE AND COST OF THE PREMIUM CAN VARY DEPENDING ON FACTORS SUCH AS THE TYPE OF VEHICLE, THE DRIVER'S AGE AND DRIVING HISTORY, AND THE COVERAGE OPTIONS SELECTED. VEHICLE INSURANCE IS OFTEN REQUIRED BY LAW AND IS AN IMPORTANT FINANCIAL TOOL TO PROTECT AGAINST UNEXPECTED COSTS ASSOCIATED WITH OWNING AND OPERATING A VEHICLE.
DURATION
6 MONTHS TO 3 YEARS
PAYMENT PLAN
MONTHLY/ ANNUAL/ ONE TIME
PAYOUT
REIMBURSEMENT OF COSTS IN ACCORDANCE WITH SCHEME SPECIFICATIONS
"""
    elif message.lower() == "travel":
        response = """TRAVEL INSURANCE
TRAVEL INSURANCE IS A TYPE OF INSURANCE THAT PROVIDES COVERAGE FOR UNEXPECTED EVENTS THAT CAN OCCUR WHILE TRAVELING, SUCH AS TRIP CANCELLATION, MEDICAL EMERGENCIES, AND LOST OR STOLEN LUGGAGE. IN EXCHANGE FOR PAYING A PREMIUM, THE INSURER AGREES TO PAY FOR CERTAIN COSTS ASSOCIATED WITH THESE EVENTS, SUCH AS MEDICAL EXPENSES, TRIP INTERRUPTION OR CANCELLATION FEES, AND REIMBURSEMENT FOR LOST OR STOLEN ITEMS.TRAVEL INSURANCE POLICIES CAN VARY IN COVERAGE AND COST DEPENDING ON THE TYPE OF TRIP AND THE INDIVIDUAL'S NEEDS. SOME POLICIES MAY INCLUDE COVERAGE FOR ADVENTURE ACTIVITIES, SUCH AS SKIING OR SCUBA DIVING, WHILE OTHERS MAY NOT. ADDITIONALLY, POLICIES MAY HAVE EXCLUSIONS AND LIMITATIONS, SO IT'S IMPORTANT TO CAREFULLY REVIEW THE POLICY BEFORE PURCHASING.
DURATION
DURATION OF TRAVEL OR 1 YEAR
PAYMENT PLAN
ONE TIME PAYMENT
PAYOUT
REIMBURSEMENT OF COSTS IN ACCORDANCE WITH SCHEME SPECIFICATIONS
"""
    elif message.lower() == "property":
        response = """PROPERTY INSURANCE
PROPERTY INSURANCE IS A TYPE OF INSURANCE THAT PROVIDES FINANCIAL PROTECTION TO PROPERTY OWNERS IN THE EVENT OF DAMAGE, THEFT, OR LOSS OF THEIR PROPERTY. PROPERTY INSURANCE CAN COVER A WIDE RANGE OF ASSETS, INCLUDING HOMES, RENTAL PROPERTIES, COMMERCIAL BUILDINGS, AND PERSONAL BELONGINGS.IN EXCHANGE FOR PAYING A PREMIUM, THE INSURER AGREES TO PAY FOR CERTAIN COSTS ASSOCIATED WITH COVERED EVENTS, SUCH AS REPAIRS OR REPLACEMENT OF DAMAGED PROPERTY. THE AMOUNT OF COVERAGE AND COST OF THE PREMIUM CAN VARY DEPENDING ON FACTORS SUCH AS THE VALUE OF THE PROPERTY, THE TYPE OF COVERAGE SELECTED, AND ANY ADDITIONAL OPTIONS CHOSEN.
DURATION
3 MONTHS TO 10 YEARS
PAYMENT PLAN
MONTHLY/ ANUALLY/ ONE TIME
PAYOUT
REIMBURSEMENT OF COSTS IN ACCORDANCE TO SCHEME SPECIFICATIONS
"""
    elif message.lower() == "a":
        response = """TERM INSURANCE
TERM INSURANCE IS A TYPE OF LIFE INSURANCE THAT PROVIDES COVERAGE
FOR A SPECIFIED PERIOD OF TIME, SUCH AS 10, 20, OR 30 YEARS. IF THE
INSURED INDIVIDUAL PASSES AWAY DURING THE TERM OF THE POLICY, THE
INSURANCE COMPANY PAYS A DEATH BENEFIT TO THE DESIGNATED
BENEFICIARIES.IT ACCUMULATES CORPUS OVER TIME AND PAYS OUT AT
MATURITY.
DURATION
5 YEARS TO 40 YEARS
PAYMENT PLAN
MONTHLY/ QUATERLY/ YEARLY
PAYOUT
IF THE PERSON INSURED WITHIN THE TENURE, INSURANCE COVERAGE IS
PAID TO THE BENEFICIARY

OR

AT THE END OF THE TENURE, MATURITY AMOUNT IS PAID OUT TO THE POLICY
HOLDER"""
    elif message.lower() == "b":
        response = """CRITICAL ILLNESS INSURANCE
HEALTH INSURANCE SPECIFIC TO DISEASES, ALSO KNOWN AS CRITICAL ILLNESS INSURANCE, IS A TYPE OF INSURANCE POLICY THAT PROVIDES COVERAGE FOR A SPECIFIC LIST OF CRITICAL ILLNESSES OR DISEASES. CRITICAL ILLNESSES COVERED MAY VARY DEPENDING ON THE POLICY, BUT TYPICALLY INCLUDE CANCER, HEART ATTACK, STROKE, KIDNEY FAILURE, AND OTHER SERIOUS ILLNESSES. WHEN A POLICYHOLDER IS DIAGNOSED WITH A COVERED CRITICAL ILLNESS, THE POLICY WILL PAY OUT A LUMP SUM AMOUNT, WHICH CAN BE USED TO COVER MEDICAL EXPENSES, LOSS OF INCOME, OR ANY OTHER EXPENSES INCURRED DURING THE TREATMENT AND RECOVERY PROCESS. THE PAYOUT AMOUNT IS USUALLY PRE-DETERMINED AND BASED ON THE SEVERITY OF THE ILLNESS.
DURATION
3 MONTHS TO 3 YEARS
PAYMENT PLAN
MONTHLY/ ANNUAL/ ONE TIME
PAYOUT
THE BENEFICIARIES WILL RECEIVE THE INSURANCE COVERAGE IF THE PERSON INSURED DIES DUE TO THE CRITICAL ILLNESS.
OR
THE POLICY HOLDER GETS MATURITY AMOUT AT EXPIRATION OF SCHEME
"""
    elif message.lower() == "c":
        response = """UNIT LINKED PLANS
UNIT-LINKED INSURANCE PLANS (ULIPS) ARE A TYPE OF INSURANCE PRODUCT THAT COMBINES THE BENEFITS OF INSURANCE COVERAGE WITH INVESTMENT OPPORTUNITIES. UNDER A ULIP, A PORTION OF THE PREMIUM PAID BY THE POLICYHOLDER IS ALLOCATED TOWARDS INSURANCE COVERAGE, WHILE THE REMAINING AMOUNT IS INVESTED IN VARIOUS INVESTMENT OPTIONS SUCH AS MUTUAL FUNDS, STOCKS, OR BONDS.THE POLICYHOLDER HAS THE FLEXIBILITY TO CHOOSE THE INVESTMENT OPTIONS THEY PREFER, AND THE VALUE OF THE INVESTMENT PORTION OF THE POLICY CAN FLUCTUATE BASED ON MARKET CONDITIONS. THE POLICYHOLDER CAN ALSO MAKE ADDITIONAL INVESTMENTS OR WITHDRAW FUNDS FROM THE POLICY, SUBJECT TO CERTAIN TERMS AND CONDITIONS.THE INSURANCE COVERAGE PROVIDED BY A ULIP TYPICALLY INCLUDES A DEATH BENEFIT, WHICH PAYS OUT A LUMP SUM TO THE POLICYHOLDER'S BENEFICIARIES IN THE EVENT OF THEIR DEATH. SOME ULIPS MAY ALSO INCLUDE ADDITIONAL BENEFITS SUCH AS ACCIDENTAL DEATH COVERAGE OR DISABILITY COVERAGE.ULIPS CAN BE A USEFUL FINANCIAL TOOL FOR INDIVIDUALS WHO WANT TO COMBINE INSURANCE COVERAGE WITH INVESTMENT OPPORTUNITIES. HOWEVER, IT'S IMPORTANT TO CAREFULLY REVIEW THE TERMS AND CONDITIONS OF A ULIP POLICY, AS WELL AS THE FEES AND CHARGES ASSOCIATED WITH THE POLICY, TO ENSURE THAT IT MEETS YOUR NEEDS AND FITS YOUR FINANCIAL GOALS.

(UNIT-LINKED INSURANCE):UNIT LINKED INVESTMENT PLANS
A UNIT LINKED INVESTMENT PLAN (ULIP) IS A TYPE OF INSURANCE PLAN THAT OFFERS BOTH LIFE INSURANCE COVERAGE AND INVESTMENT OPPORTUNITIES. WHEN YOU PURCHASE A ULIP, A PORTION OF YOUR PREMIUM IS ALLOCATED TOWARDS LIFE INSURANCE COVERAGE, WHILE THE REMAINING PORTION IS INVESTED IN VARIOUS MARKET-LINKED INVESTMENT FUNDS SUCH AS EQUITY, DEBT OR A MIX OF BOTH.
DURATION:
5 YEARS TO 10 YEARS
PAYMENT PLAN:
MONTHLY/ QUATERLY/ ANUALLY/ ONE TIME
PAYOUT:
THE INSURANCE COVERAGE IS PAID OUT TO THE BENEFICIARY IN CASE THE PERSON INSURED DIES.
OR
THE VALUE OF INVESTMENT UNIT AT MARKET VALUE IS PAID TO THE POLICY-HOLDER.
"""
    elif message.lower() == "d":
        response = "type 1 for 'one time premium plan'. 2 for 'endownment plan'. 3 for 'whole life insurance'. 4 for 'money back plan'. 5 for 'child plans' " 
    elif message.lower() == "e":
        response = """NON LINKED PLANS
NON-LINKED INSURANCE PLANS ARE A TYPE OF INSURANCE PRODUCT THAT
PROVIDES LIFE INSURANCE COVERAGE WITHOUT ANY INVESTMENT
COMPONENT. UNLIKE LINKED INSURANCE PLANS, WHICH COMBINE
INSURANCE COVERAGE WITH INVESTMENT OPPORTUNITIES, NON-LINKED
PLANS ONLY PROVIDE INSURANCE PROTECTION AND DO NOT OFFER ANY
INVESTMENT OPTIONS.NON-LINKED PLANS TYPICALLY PROVIDE A FIXED
PREMIUM PAYMENT OVER THE POLICY TERM, AND THE POLICYHOLDER CAN
CHOOSE THE AMOUNT OF COVERAGE THEY NEED BASED ON THEIR
FINANCIAL NEEDS AND GOALS. IF THE POLICYHOLDER PASSES AWAY
DURING THE POLICY TERM, THE BENEFICIARIES RECEIVE A LUMP SUM
PAYMENT, WHICH IS TYPICALLY TAX-FREE.NON-LINKED PLANS CAN BE A
USEFUL FINANCIAL TOOL FOR INDIVIDUALS WHO WANT TO PROVIDE
FINANCIAL PROTECTION FOR THEIR LOVED ONES IN THE EVENT OF THEIR
UNEXPECTED DEATH. THE PREMIUMS FOR NON-LINKED PLANS ARE
GENERALLY LOWER THAN LINKED PLANS, AS THERE IS NO INVESTMENT
COMPONENT. HOWEVER, IT&#39;S IMPORTANT TO CAREFULLY REVIEW THE
TERMS AND CONDITIONS OF A NON-LINKED INSURANCE POLICY TO ENSURE
THAT IT MEETS YOUR NEEDS AND PROVIDES THE APPROPRIATE COVERAGE
FOR YOUR SITUATION."""
    elif message.lower() == "1":
        response = """ONE TIME PREMIUM PLAN
ONE-TIME PREMIUM PLAN IS A TYPE OF LIFE INSURANCE POLICY IN WHICH THE POLICYHOLDER PAYS THE ENTIRE PREMIUM AMOUNT UPFRONT IN A SINGLE PAYMENT. IT IS A LONG-TERM INVESTMENT PLAN THAT PROVIDES INSURANCE COVERAGE AND SAVINGS BENEFITS. IN A ONE-TIME PREMIUM PLAN, THE POLICYHOLDER PAYS A LUMP-SUM AMOUNT AT THE TIME OF POLICY INCEPTION, WHICH PROVIDES COVERAGE FOR A PREDETERMINED PERIOD, TYPICALLY RANGING FROM 5 TO 30 YEARS. THE INSURANCE COMPANY INVESTS THE PREMIUM AMOUNT IN A PORTFOLIO OF STOCKS, BONDS, AND OTHER FINANCIAL INSTRUMENTS TO GENERATE RETURNS.
DURATION
5 YEARS TO 30 YEARS
PAYMENT PLAN
ONE TIME PAYMENT
PAYOUT
IF THE PERSON IINSURED DIES WITHIN THE TENURE, THE BENEFICIARY RECEIVES INSURANCE COVERAGE
OR
AT THE END OF TENURE, THE POLICY HOLDER RECEIVES MATURITY AMOUNT
"""
    elif message.lower() == "2":
        response = """ENDOWMENT PLAN
ENDOWMENT INSURANCE PLAN IS A TYPE OF LIFE INSURANCE POLICY THAT PROVIDES BOTH INSURANCE COVERAGE AND SAVINGS BENEFITS. IT IS A LONG-TERM INVESTMENT PLAN THAT ALLOWS POLICYHOLDERS TO ACCUMULATE SAVINGS OVER A SPECIFIED PERIOD WHILE ALSO PROVIDING A DEATH BENEFIT. IN AN ENDOWMENT PLAN, THE POLICYHOLDER PAYS A FIXED PREMIUM AMOUNT FOR A PREDETERMINED PERIOD, WHICH CAN RANGE FROM 10 TO 30 YEARS. THE INSURANCE COMPANY INVESTS THE PREMIUMS IN A PORTFOLIO OF STOCKS, BONDS, AND OTHER FINANCIAL INSTRUMENTS TO GENERATE RETURNS. UPON THE POLICY'S MATURITY, THE POLICYHOLDER RECEIVES A LUMP-SUM AMOUNT EQUAL TO THE SUM ASSURED PLUS ANY ACCUMULATED BONUSES. IF THE POLICYHOLDER DIES DURING THE POLICY TERM, THE NOMINEE RECEIVES THE SUM ASSURED AS A DEATH BENEFIT.
DURATION
10 YEARS TO 30 YEARS
PAYMENT PLAN
MONTHLY/ QUATERLY/ YEARLY
PAYOUT
IF THE PERSON DIES WITHIN THE TENURE, INSURANCE COVERAGE IS PAID OUT TO THE BENEFICIARY
OR
THE POLICY BOLDER GETS A FIXED ANNUITY AFTER THE END OF TENURE
"""
    elif message.lower() == "3":
        response = """WHOLE LIFE INSURANCE
WHOLE LIFE INSURANCE IS A TYPE OF LIFE INSURANCE POLICY THAT PROVIDES COVERAGE FOR THE POLICYHOLDER'S ENTIRE LIFETIME. IT IS A LONG-TERM INVESTMENT PLAN THAT OFFERS INSURANCE COVERAGE AND SAVINGS BENEFITS. IN A WHOLE LIFE INSURANCE POLICY, THE POLICYHOLDER PAYS A FIXED PREMIUM AMOUNT FOR THE ENTIRE POLICY TERM, WHICH IS TYPICALLY THE POLICYHOLDER'S ENTIRE LIFE. THE INSURANCE COMPANY INVESTS THE PREMIUMS IN A PORTFOLIO OF STOCKS, BONDS, AND OTHER FINANCIAL INSTRUMENTS TO GENERATE RETURNS.
DURATION
O-99 YEARS
PAYMENT PLAN
MONTHLY/ QUATERLY/ YEARLY
PAYOUT
MATURITY AMOUNT IS PAID TO THE BENEFICIARY UPON DEATH OF THE PERSON INSURED
"""
    elif message.lower() == "4":
        response = """MONEY BACK INSURANCE PLAN
MONEY BACK INVESTMENT PLAN IS A TYPE OF LIFE INSURANCE POLICY THAT PROVIDES BOTH INSURANCE COVERAGE AND PERIODIC PAYOUTS THROUGHOUT THE POLICY TERM. IT IS A LONG-TERM INVESTMENT PLAN THAT ALLOWS POLICYHOLDERS TO RECEIVE A PORTION OF THE SUM ASSURED AT REGULAR INTERVALS. IN A MONEY BACK PLAN, THE POLICYHOLDER PAYS A FIXED PREMIUM AMOUNT FOR A PREDETERMINED PERIOD, WHICH CAN RANGE FROM 10 TO 25 YEARS. THE INSURANCE COMPANY INVESTS THE PREMIUMS IN A PORTFOLIO OF STOCKS, BONDS, AND OTHER FINANCIAL INSTRUMENTS TO GENERATE RETURNS. DURING THE POLICY TERM, THE POLICYHOLDER RECEIVES A PERCENTAGE OF THE SUM ASSURED AS A CASH PAYOUT AT REGULAR INTERVALS, TYPICALLY EVERY 5 YEARS. THESE PAYOUTS SERVE AS A SOURCE OF REGULAR INCOME AND CAN BE USED FOR VARIOUS PURPOSES, SUCH AS MEETING SHORT-TERM FINANCIAL GOALS OR COVERING RECURRING EXPENSES.
DURATION
10 YEARS TO 25 YEARS
PAYMENT PLAN
MONTHLY/ QUATERLY/ YEARLY
PAYOUT
IF THE PERSON INSURED DIES WITHIN TENURE, THE BENEFICIARY IS PAID THE INSURANCEE COVERAGE. THE POLICY HOLDERS ARE ALSO ACCUMULATED CORPUS AT FIXED INTERVALS.
"""
    elif message.lower() == "5":
        response = """CHILD PLANS
CHILD PLANS ARE INVESTMENT PLANS DESIGNED SPECIFICALLY TO SECURE A CHILD'S FUTURE FINANCIALLY. THEY ARE LONG-TERM INVESTMENTS AND CAN BE TAKEN BY PARENTS OR GUARDIANS ON BEHALF OF THEIR CHILDREN. CHILD PLANS PROVIDE A LUMP-SUM AMOUNT ON MATURITY, WHICH CAN BE USED FOR VARIOUS EXPENSES SUCH AS EDUCATION, MARRIAGE, OR ANY OTHER FINANCIAL REQUIREMENTS OF THE CHILD. CHILD PLANS TYPICALLY PROVIDE LIFE INSURANCE COVERAGE FOR THE PARENT OR GUARDIAN WHO PURCHASES THE PLAN. IN CASE OF THE PARENT OR GUARDIAN'S UNTIMELY DEMISE, THE CHILD WILL STILL RECEIVE THE BENEFITS OF THE POLICY. ADDITIONALLY, SOME CHILD PLANS ALSO OFFER PERIODIC PAYOUTS TO THE CHILD AT SPECIFIC MILESTONES IN THEIR LIFE. OVERALL, CHILD PLANS PROVIDE A COMPREHENSIVE FINANCIAL SOLUTION FOR SECURING A CHILD'S FUTURE, ENSURING THEIR FINANCIAL NEEDS ARE MET EVEN IN THE PARENT OR GUARDIAN'S ABSENCE.
DURATION
5 YEARS TO 40 YEARS
PAYMENT PLAN
MONTHLY/ QUATERLY/ YEARLY
PAYOUT
IF THE GUARDIAN OF THE CHILD DIES WITHIN THE TENURE, INSURANCE COVERAGE IS GIVEN TO THE CHILD
OR
AT THE END OF TENURE, THE CHILD GETS MATURITY AMOUNT
"""


    elif message.lower() == "s":
        response = "first ill need to know some more about you...please input your preffered duration:  "

    elif message.lower() == "recurring deposits":
        response = """RECURRING DEPOSITS
RECURRING DEPOSITS ARE A TYPE OF SAVINGS ACCOUNT OFFERED BY
BANKS AND FINANCIAL INSTITUTIONS THAT ALLOW INDIVIDUALS TO MAKE
REGULAR DEPOSITS OF A FIXED AMOUNT FOR A PRE-DETERMINED PERIOD.
THE DEPOSITS CAN BE MADE ON A MONTHLY OR QUARTERLY BASIS, AND
THE INTEREST RATES ARE FIXED FOR THE DURATION OF THE DEPOSIT. AT
THE END OF THE DEPOSIT PERIOD, THE ACCUMULATED AMOUNT, INCLUDING
THE INTEREST EARNED, IS PAID BACK TO THE DEPOSITOR. RECURRING
DEPOSITS ARE A LOW-RISK INVESTMENT OPTION THAT PROVIDES
GUARANTEED RETURNS AND ENCOURAGES REGULAR SAVINGS.
RISK FACTOR
LOW
DURATION
6 MONTHS TO 10 YEARS
RATE OF RETURN
2.50% TO 7.50% P.A.
LIQUIDITY
PARTIALLY LIQUID
TAX IMPLICATIONS
10% TDS ON INTEREST ABOVE RS 40000 P.A."""
    elif message.lower() == "FIXED DEPOSITS":
        response = """FIXED DEPOSITS
FIXED DEPOSITS (FDS) ARE FINANCIAL INSTRUMENTS OFFERED BY BANKS
AND FINANCIAL INSTITUTIONS THAT PROVIDE A FIXED RATE OF INTEREST
FOR A SPECIFIED PERIOD. THEY OFFER A GUARANTEED RETURN AND ARE
CONSIDERED SAFE, MAKING THEM A SUITABLE INVESTMENT OPTION FOR
RISK-AVERSE INVESTORS. HOWEVER, THEY OFFER LOWER RETURNS
COMPARED TO OTHER INVESTMENT OPTIONS AND MAY INCUR PENALTY
FEES IF WITHDRAWN BEFORE MATURITY.
RISK FACTOR
VERY LOW
DURATION
3 MONTHS TO 10 YEARS
RATE OF RETURN
2.50% TO 7.50% P.A.
LIQUIDITY
PARTIALLY LIQUID
TAX IMPLICATION
10% TDS ON INTEREST ABOVE Rs 40000 P.A."""
        
    elif message.lower() == "SAVING ACCOUNTS":
        response = """SAVINGS ACCOUNT
A SAVINGS ACCOUNT IS A TYPE OF DEPOSIT ACCOUNT OFFERED BY BANKS
AND OTHER FINANCIAL INSTITUTIONS THAT ALLOW CUSTOMERS TO SAVE
AND EARN INTEREST ON THEIR MONEY. THE ACCOUNT HOLDER CAN DEPOSIT
AND WITHDRAW MONEY AS PER THEIR CONVENIENCE, AND THE INTEREST
RATE ON SAVINGS ACCOUNTS IS TYPICALLY LOWER THAN THAT OF OTHER
INVESTMENT OPTIONS.
RISK FACTOR
VERY LOW
DURATION
ANY DURATION
RATE OF RETURN
2.50% P.A.
LIQUIDITY
LIQUID
TAX IMPLICATION
INTEREST ABOVE Rs 10000 P.A. IS TAXED ACCORDING TO THE TAX SLAB"""
        
    elif message.lower() == "NATIONAL SAVING CERTIFICATES":
        response = """NATIONAL PENSION SCHEME
The National Pension System (NPS) is a retirement savings scheme launched by
the Indian government in 2004. It is a voluntary, defined contribution retirement
savings plan available to all citizens of India, including the self-employed and
unorganized sectors. Under the NPS, individuals can open a retirement account
and make contributions towards it. The contributions are invested in various
pension funds, and the returns on the investments are based on the performance
of these funds. The scheme offers two types of accounts - Tier I and Tier II. The
Tier I account is a mandatory account, and it comes with a lock-in period until the
age of 60. Partial withdrawals are allowed for certain specific purposes like
education, marriage, etc. The Tier II account is a voluntary account that offers
more flexibility to withdraw money as and when required, but it does not have the
tax benefits of the Tier I account."""
        
    elif message.lower() == "SUKANYA SAMRIDHI YOJANA ":
        response = """SUKANYA SAMRIDDHI YOJANA
Sukanya Samriddhi Yojana (SSY) is a government-backed savings scheme in
India that aims to promote the welfare of the girl child and encourage parents to
save for their daughter&#39;s education and marriage expenses.Under this scheme,
parents or legal guardians can open an account in the name of their girl child
before she turns 10 years old. The account can be opened with a minimum
deposit of Rs. 250 and a maximum of Rs. 1.5 lakh per annum. The account
matures after 21 years, but partial withdrawals are allowed after the girl child
turns 18 years old.The scheme offers a high rate of interest, which is determined
by the government and revised every quarter. funds can only be used for the
education and marriage expenses of the girl child. the account can only be
opened for up to two girl children per family. the Sukanya Samriddhi Yojana is a
good option for parents looking to save for their daughter&#39;s education and
marriage expenses.
RISK FACTOR
VERY LOW
DURATION
21 YEARS
RATE OF RETURN
7.6% P.A.
LIQUIDITY
ILLIQUID
TAX IMPLICATION
COMPLETELY TAX-FREE"""
        
    elif message.lower() == "PROVIDENT FUND":
        response = """PROVIDENT FUND
THE PROVIDENT FUND (PF) IN INDIA IS A RETIREMENT SAVINGS SCHEME
ESTABLISHED UNDER THE EMPLOYEES&#39; PROVIDENT FUNDS AND
MISCELLANEOUS PROVISIONS ACT, 1952. IT IS A GOVERNMENT-MANAGED
FUND THAT REQUIRES BOTH EMPLOYEES AND EMPLOYERS TO CONTRIBUTE
A FIXED PERCENTAGE OF THE EMPLOYEE&#39;S SALARY EVERY MONTH. THE
CONTRIBUTIONS ARE DEPOSITED INTO AN EMPLOYEE&#39;S PROVIDENT FUND
ACCOUNT, WHICH IS MANAGED BY THE EMPLOYEES&#39; PROVIDENT FUND
ORGANISATION (EPFO). THE ACCUMULATED BALANCE IN THE PROVIDENT
FUND ACCOUNT CAN BE WITHDRAWN BY THE EMPLOYEE AT THE TIME OF
RETIREMENT, OR IN CASE OF CERTAIN EMERGENCIES. THE PROVIDENT FUND
SCHEME IS APPLICABLE TO ALL SALARIED EMPLOYEES IN INDIA, WHO EARN
UP TO A CERTAIN AMOUNT PER MONTH, AS DETERMINED BY THE
GOVERNMENT.
RISK FACTOR
LOW
DURATION
ANY
RATE OF RETURN
8.15% P.A.
LIQUIDITY
ILLIQUID
CAN ONLY BE WITHDRAWN UNDER SPECIAL CLAUSES
TAX IMPLICATION
IF WITHDRAWN BEFORE 5 YEARS:-
10% TDS FLAT ON ALL INTERESTS ACCURED ABOVE Rs 50000.
IF WITHDRAWN IN ACCORDANCE WITH GOVERNMENT PRESCRIBED MATURITY
DATES AND CLAUSES:-
INTEREST INCOME FROM EMPLOYEES CONTRIBUTION OR EXCESS
VOLUNTARY CONTRIBUTION FROM EMPLOYEE OR EMPLOYER EXCEEDING Rs

250000 IN A FINANCIAL YEAR IS SUBJECTED TO TAXES ACCORDING TO THE
TAX SLABS."""

    elif message.lower() == "stocks":
        response = """STOCKS
STOCK MARKET INVESTMENTS INVOLVE BUYING SHARES OF PUBLICLY-
TRADED COMPANIES IN THE HOPE OF EARNING A RETURN ON THE
INVESTMENT, TYPICALLY THROUGH A COMBINATION OF CAPITAL GAINS AND
DIVIDENDS.WHEN AN INVESTOR BUYS SHARES OF A COMPANY, THEY
BECOME A PART OWNER OF THAT COMPANY AND HAVE A CLAIM ON ITS
PROFITS. IF THE COMPANY PERFORMS WELL AND ITS EARNINGS GROW, THE
VALUE OF THE SHARES WILL TYPICALLY INCREASE OVER TIME, ALLOWING
THE INVESTOR TO SELL THEM FOR A PROFIT.IN ADDITION TO CAPITAL GAINS,
MANY PUBLICLY-TRADED COMPANIES ALSO PAY DIVIDENDS TO THEIR
SHAREHOLDERS, WHICH ARE A PORTION OF THE COMPANY&#39;S PROFITS THAT
ARE DISTRIBUTED TO INVESTORS ON A REGULAR BASIS. DIVIDENDS CAN
PROVIDE A STEADY SOURCE OF INCOME FOR INVESTORS, PARTICULARLY IN
TIMES OF MARKET VOLATILITY.HOWEVER, INVESTING IN THE STOCK MARKET
DOES CARRY A DEGREE OF RISK. STOCK PRICES CAN BE AFFECTED BY A
VARIETY OF FACTORS, INCLUDING CHANGES IN THE OVERALL ECONOMY,
INDUSTRY TRENDS, AND COMPANY-SPECIFIC ISSUES SUCH AS MANAGEMENT
CHANGES OR PRODUCT RECALLS. AS A RESULT, STOCK MARKET
INVESTMENTS CAN BE VOLATILE, AND INVESTORS MAY EXPERIENCE LOSSES
IF THE MARKET OR INDIVIDUAL COMPANIES PERFORM POORLY."
"""
   

    elif message.lower() == "mutual funds":
        response = """MUTUAL FUNDS
A MUTUAL FUND IS A TYPE OF INVESTMENT VEHICLE THAT POOLS MONEY
FROM MULTIPLE INVESTORS TO PURCHASE A DIVERSIFIED PORTFOLIO OF
STOCKS, BONDS, OR OTHER SECURITIES. THE FUND IS MANAGED BY A
PROFESSIONAL FUND MANAGER WHO USES THEIR EXPERTISE TO SELECT
SECURITIES THAT THEY BELIEVE WILL PROVIDE ATTRACTIVE RETURNS
WHILE MANAGING THE RISKS ASSOCIATED WITH INVESTING IN FINANCIAL
MARKETS. MUTUAL FUNDS CAN INVEST IN A VARIETY OF SECURITIES,
INCLUDING STOCKS, BONDS, REAL ESTATE, COMMODITIES, AND
ALTERNATIVE INVESTMENTS. THE OBJECTIVE OF THE MUTUAL FUND AND
THE TYPES OF SECURITIES IT INVESTS IN VARY DEPENDING ON THE FUND&#39;S
INVESTMENT STRATEGY. MUTUAL FUNDS CAN PROVIDE INVESTORS WITH A
CONVENIENT AND ACCESSIBLE WAY TO INVEST IN FINANCIAL MARKETS
WHILE BENEFITING FROM PROFESSIONAL MANAGEMENT AND
DIVERSIFICATION."""
    elif message.lower() == "money market funds":
        response = """MONEY MARKET FUNDS
MONEY MARKET FUNDS ARE A TYPE OF MUTUAL FUND THAT INVESTS IN
SHORT-TERM, LOW-RISK FIXED-INCOME SECURITIES, SUCH AS GOVERNMENT
SECURITIES, CERTIFICATES OF DEPOSIT, AND COMMERCIAL PAPER. THESE
FUNDS AIM TO PROVIDE INVESTORS WITH A LOW-RISK AND LIQUID
INVESTMENT OPTION THAT PROVIDES A STABLE RETURN ON INVESTMENT.
MONEY MARKET FUNDS TYPICALLY INVEST IN SECURITIES WITH MATURITIES
OF LESS THAN ONE YEAR, WHICH MAKES THEM LESS VOLATILE THAN OTHER
TYPES OF MUTUAL FUNDS.
RISK FACTOR
VERY LOW
DURATION
ANY
RATE OF RETURN
6% TO 7%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "fixed income funds":
        response = """FIXED INCOME FUNDS
FIXED INCOME FUNDS ARE A TYPE OF MUTUAL FUND THAT INVESTS
PRIMARILY IN FIXED-INCOME SECURITIES, SUCH AS BONDS, TREASURY
BILLS, AND OTHER DEBT INSTRUMENTS. THESE FUNDS AIM TO PROVIDE
INVESTORS WITH A STABLE STREAM OF INCOME THROUGH INTEREST
PAYMENTS WHILE PRESERVING THE CAPITAL INVESTED.FIXED INCOME
FUNDS CAN INVEST IN A VARIETY OF BONDS, INCLUDING GOVERNMENT
BONDS, CORPORATE BONDS, MUNICIPAL BONDS, AND MORTGAGE-BACKED
SECURITIES. THE FUND&#39;S PORTFOLIO MAY CONSIST OF BONDS WITH
VARYING MATURITIES, CREDIT RATINGS, AND INTEREST RATES, WHICH CAN
AFFECT THE RETURNS AND RISKS OF THE FUND."""
    elif message.lower() == "corporate bond fund":
        response = """CORPORATE BOND FUND
A CORPORATE BOND FUND IS A TYPE OF MUTUAL FUND THAT INVESTS
PRIMARILY IN BONDS ISSUED BY CORPORATIONS. THESE BONDS ARE DEBT
SECURITIES ISSUED BY COMPANIES TO RAISE CAPITAL FOR VARIOUS
PURPOSES, SUCH AS EXPANDING THEIR OPERATIONS, FINANCING
ACQUISITIONS, OR REFINANCING EXISTING DEBT.
RISK FACTOR
LOW
DURATION
ANY
RATE OF RETURN
8% TO 9%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "government bond fund":
        response = """GOVERNMENT BOND FUND
A GOVERNMENT BOND FUND IS A TYPE OF MUTUAL FUND THAT INVESTS
PRIMARILY IN BONDS ISSUED BY GOVERNMENTS. THESE BONDS ARE DEBT
SECURITIES ISSUED BY CENTRAL OR STATE GOVERNMENTS TO RAISE
CAPITAL FOR VARIOUS PURPOSES, SUCH AS FINANCING GOVERNMENT
SPENDING OR INFRASTRUCTURE DEVELOPMENT. GOVERNMENT BOND
FUNDS CAN INVEST IN A VARIETY OF GOVERNMENT BONDS, INCLUDING
TREASURY BILLS, TREASURY NOTES, AND TREASURY BONDS.
RISK FACTOR
VERY LOW
DURATION
ANY
RATE OF RETURN
7% TO 8%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "mixed bond fund":
        response = """MIXED BOND FUND
A MIXED BOND FUND, ALSO KNOWN AS A HYBRID BOND FUND, IS A TYPE OF
MUTUAL FUND THAT INVESTS IN A MIX OF GOVERNMENT BONDS,
CORPORATE BONDS, AND OTHER FIXED INCOME SECURITIES. MIXED BOND
FUNDS PROVIDE INVESTORS WITH A DIVERSIFIED PORTFOLIO OF FIXED
INCOME SECURITIES THAT AIM TO GENERATE REGULAR INCOME WHILE
MANAGING RISK.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
9% TO 11%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "high yield bond funds":
        response = """HIGH YIELD CORPORATE FUND
A HIGH YIELD BOND FUND IS A TYPE OF MUTUAL FUND THAT INVESTS IN
BONDS ISSUED BY COMPANIES WITH LOWER CREDIT RATINGS. THESE
BONDS ARE ALSO KNOWN AS &quot;JUNK&quot; BONDS BECAUSE THEY ARE
CONSIDERED RISKIER THAN INVESTMENT-GRADE BONDS, WHICH ARE ISSUED
BY COMPANIES WITH HIGHER CREDIT RATINGS. HIGH YIELD BOND FUNDS AIM
TO GENERATE HIGHER RETURNS FOR INVESTORS BY INVESTING IN A
DIVERSIFIED PORTFOLIO OF LOWER-RATED CORPORATE BONDS.
RISK FACTOR
HIGH
DURATION
ANY
RATE OF RETURN
11% TO 13%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "equity funds":
        response = """EQUITY FUNDS
EQUITY FUNDS ARE A TYPE OF MUTUAL FUND THAT INVESTS PRIMARILY IN
STOCKS, GIVING INVESTORS EXPOSURE TO A DIVERSIFIED PORTFOLIO OF
EQUITIES. EQUITY FUNDS ARE DESIGNED TO PROVIDE INVESTORS WITH THE
POTENTIAL FOR LONG-TERM CAPITAL APPRECIATION BY INVESTING IN
COMPANIES THAT ARE EXPECTED TO GROW AND INCREASE IN VALUE OVER
TIME.EQUITY FUNDS CAN INVEST IN A VARIETY OF STOCKS, INCLUDING
LARGE-CAP, MID-CAP, AND SMALL-CAP COMPANIES, AS WELL AS GROWTH
AND VALUE STOCKS. THE FUND&#39;S INVESTMENT STRATEGY AND OBJECTIVES
CAN VARY DEPENDING ON THE FUND&#39;S FOCUS AND THE INVESTMENT STYLE
OF THE FUND MANAGER."""
    elif message.lower() == "bluechip equity funds":
        response = """BLUE CHIP EQUITY FUND
BLUE CHIP EQUITY FUNDS ARE MUTUAL FUNDS THAT INVEST PRIMARILY IN
BLUE CHIP STOCKS OR SHARES OF LARGE, WELL-ESTABLISHED COMPANIES
WITH A STRONG TRACK RECORD OF PERFORMANCE AND STABILITY. THESE
COMPANIES ARE GENERALLY LEADERS IN THEIR RESPECTIVE INDUSTRIES
AND ARE KNOWN FOR THEIR FINANCIAL STRENGTH, STRONG MANAGEMENT,
AND STABLE EARNINGS.
RISK FACTOR
LOW
DURATION
ANY
RATE OF RETURN
8%-10%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000"""
    elif message.lower() == "large cap equity fund":
        response = """LARGE CAP MUTUAL FUNDS
A LARGE CAP MUTUAL FUND IN INDIA IS A TYPE OF EQUITY MUTUAL FUND
THAT PRIMARILY INVESTS IN STOCKS OF LARGE-CAP COMPANIES, WHICH
HAVE MARKET CAPITALIZATION OF MORE THAN 5000 CRORE RUPEES. THESE
COMPANIES HAVE A PROVEN TRACK RECORD OF STABLE EARNINGS.
RISK FACTOR
LOW
DURATION
ANY
RATE OF RETURN
10% TO 12%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000."""
    elif message.lower() == "small cap equity fund":
        response = """SMALL CAP MUTUAL FUNDS
SMALL CAP MUTUAL FUNDS IN INDIA ARE EQUITY MUTUAL FUNDS THAT
INVEST PRIMARILY IN THE STOCKS OF SMALL-SIZED COMPANIES LISTED ON
THE INDIAN STOCK EXCHANGES. SMALL CAP COMPANIES ARE THOSE WITH
RELATIVELY SMALL MARKET CAPITALIZATION, TYPICALLY LESS THAN RS.
5000 CRORES. THESE COMPANIES HAVE A HIGHER POTENTIAL FOR GROWTH
THAN LARGER COMPANIES BUT ARE ALSO CONSIDERED TO BE MORE
VOLATILE AND RISKY
RISK FACTOR
HIGH
DURATION
ANY
RATE OF RETURN
14% TO 16%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000."""
    elif message.lower() == "mid cap equity fund":
        response = """MID CAP EQUITY FUND
MID CAP MUTUAL FUNDS ARE A TYPE OF EQUITY FUND THAT
INVESTS PRIMARILY IN STOCKS OF MID-SIZED COMPANIES. THESE
COMPANIES ARE GENERALLY CONSIDERED TO BE IN THE MIDDLE RANGE OF
THE MARKET CAPITALIZATION SPECTRUM, BETWEEN LARGE CAP AND SMALL
CAP COMPANIES. MID CAP COMPANIES ARE TYPICALLY ESTABLISHED FIRMS
THAT HAVE ALREADY UNDERGONE A PHASE OF GROWTH AND ARE NOW
POISED FOR FURTHER EXPANSION.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
12% TO 14%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000."""
    elif message.lower() == "hybrid funds":
        response = """HYBRID FUNDS
HYBRID FUNDS, ALSO KNOWN AS BALANCED FUNDS, ARE A TYPE OF
MUTUAL FUND THAT INVESTS IN A COMBINATION OF STOCKS AND BONDS, AS
WELL AS OTHER SECURITIES, SUCH AS MONEY MARKET INSTRUMENTS AND
ALTERNATIVE INVESTMENTS. HYBRID FUNDS AIM TO PROVIDE INVESTORS
WITH A DIVERSIFIED PORTFOLIO OF SECURITIES THAT CAN PROVIDE BOTH
GROWTH AND INCOME POTENTIAL.HYBRID FUNDS CAN VARY IN THEIR
INVESTMENT MIX, WITH SOME FUNDS INVESTING PRIMARILY IN STOCKS AND
OTHERS INVESTING PRIMARILY IN BONDS. THE ALLOCATION TO STOCKS AND
BONDS CAN ALSO VARY, WITH SOME FUNDS MAINTAINING A FIXED
ALLOCATION AND OTHERS ADJUSTING THE ALLOCATION BASED ON MARKET
CONDITIONS AND THE INVESTMENT OBJECTIVES OF THE FUND."""
    elif message.lower() == "equity oriented hybrid funds":
        response = """EQUITY ORIENTED HYBRID FUNDS
EQUITY-ORIENTED HYBRID FUNDS ARE A TYPE OF MUTUAL FUND THAT
INVESTS IN A COMBINATION OF EQUITY SHARES AND DEBT SECURITIES.
THESE FUNDS AIM TO PROVIDE INVESTORS WITH EXPOSURE TO THE
POTENTIAL HIGH RETURNS OF EQUITY INVESTMENTS WHILE ALSO
PROVIDING SOME STABILITY AND INCOME FROM THE DEBT INVESTMENTS.IN
EQUITY-ORIENTED HYBRID FUNDS, A MINIMUM OF 65% OF THE PORTFOLIO IS
INVESTED IN EQUITY SHARES, WHILE THE REMAINING AMOUNT IS INVESTED
IN DEBT SECURITIES. THE EQUITY PORTION OF THE PORTFOLIO CAN BE
INVESTED IN LARGE-CAP, MID-CAP, OR SMALL-CAP STOCKS, DEPENDING ON
THE INVESTMENT STRATEGY OF THE FUND MANAGER. THE DEBT PORTION OF
THE PORTFOLIO IS INVESTED IN FIXED INCOME SECURITIES, SUCH AS
GOVERNMENT BONDS, CORPORATE BONDS, OR MONEY MARKET
INSTRUMENTS.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
11% TO 12%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000"""
    elif message.lower() == "debt oriented hybrid funds":
        response = """DEBT ORIENTED HYBRID FUNDS
DEBT-ORIENTED HYBRID FUNDS ARE A TYPE OF MUTUAL FUND THAT
INVESTS PRIMARILY IN DEBT SECURITIES, SUCH AS GOVERNMENT BONDS,
CORPORATE BONDS, AND OTHER FIXED-INCOME SECURITIES. THESE FUNDS
ALSO INVEST A SMALLER PORTION OF THE PORTFOLIO IN EQUITY SHARES
TO PROVIDE SOME POTENTIAL FOR CAPITAL APPRECIATION. IN DEBT-
ORIENTED HYBRID FUNDS, AT LEAST 65% OF THE PORTFOLIO IS INVESTED IN
DEBT SECURITIES, WHILE THE REMAINING AMOUNT IS INVESTED IN EQUITY
SHARES. THE EQUITY PORTION OF THE PORTFOLIO CAN BE INVESTED IN
LARGE-CAP, MID-CAP, OR SMALL-CAP STOCKS, DEPENDING ON THE
INVESTMENT STRATEGY OF THE FUND MANAGER.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
9% TO 10%
LIQUIDITY
LIQUID
TAX IMPLICATION

IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "index funds":
        response = """INDEX FUNDS
INDEX FUNDS ARE MUTUAL FUNDS THAT INVEST IN STOCKS THAT ARE PART
OF A SPECIFIC MARKET INDEX, SUCH AS THE NIFTY 50 OR THE BSE SENSEX.
THESE FUNDS AIM TO REPLICATE THE PERFORMANCE OF THE INDEX THEY
ARE TRACKING, PROVIDING INVESTORS WITH RETURNS"""
    elif message.lower() == "nifty 50 index fund":
        response = """NIFTY 50 INDEX FUND
THE NIFTY 50 INDEX FUND IS A TYPE OF MUTUAL FUND OR EXCHANGE-
TRADED FUND (ETF) THAT TRACKS THE PERFORMANCE OF THE NIFTY 50
INDEX. THE NIFTY 50 IS A BENCHMARK INDEX OF THE NATIONAL STOCK
EXCHANGE (NSE) IN INDIA, CONSISTING OF THE 50 LARGEST AND MOST
ACTIVELY TRADED COMPANIES ACROSS VARIOUS SECTORS. THE INDEX IS
CONSIDERED A BAROMETER OF THE INDIAN STOCK MARKET AND IS WIDELY
USED BY INVESTORS TO GAUGE THE OVERALL PERFORMANCE OF THE
MARKET.
RISK FACTOR
LOW
DURATION
LOW
RATE OF RETURN
'8%-11%'
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000."""
    elif message.lower() == "sensex index fund":
        response = """SENSEX INDEX FUND
THE SENSEX INDEX FUND IS A TYPE OF MUTUAL FUND OR EXCHANGE-
TRADED FUND (ETF) THAT TRACKS THE PERFORMANCE OF THE S&amp;P BSE
SENSEX. THE S&amp;P BSE SENSEX IS THE BENCHMARK INDEX OF THE BOMBAY
STOCK EXCHANGE (BSE) IN INDIA, CONSISTING OF THE 30 LARGEST AND
MOST ACTIVELY TRADED COMPANIES ACROSS VARIOUS SECTORS. THE
INDEX IS CONSIDERED A KEY INDICATOR OF THE INDIAN STOCK MARKET AND
IS WIDELY USED BY INVESTORS TO GAUGE THE OVERALL PERFORMANCE OF
THE MARKET.
RISK FACTOR
LOW
DURATION
ANY
RATE OF RETURN
11% TO 13%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000"""
    elif message.lower() == "nifty next 50 index fund":
        response = """NIFTY NEXT 50 INDEX FUND
THE NIFTY NEXT 50 INDEX FUND IS A TYPE OF MUTUAL FUND OR EXCHANGE-
TRADED FUND (ETF) THAT TRACKS THE PERFORMANCE OF THE NIFTY NEXT
50 INDEX. THE NIFTY NEXT 50 IS A BENCHMARK INDEX OF THE NATIONAL
STOCK EXCHANGE (NSE) IN INDIA, CONSISTING OF THE 50 COMPANIES THAT
FOLLOW THE TOP 50 IN TERMS OF FREE FLOAT MARKET CAPITALIZATION.
THESE COMPANIES ARE CONSIDERED TO BE POTENTIAL FUTURE BLUE-CHIP
COMPANIES, AND HAVE A HIGHER RISK-RETURN PROFILE THAN THE NIFTY 50
INDEX.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
11% TO 14%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000."""
    elif message.lower() == "nasdaq composite index fund":
        response = """NASDAQ COMPOSITE INDEX FUND
THE NASDAQ COMPOSITE INDEX FUND IS A TYPE OF MUTUAL FUND OR
EXCHANGE-TRADED FUND (ETF) THAT TRACKS THE PERFORMANCE OF THE
NASDAQ COMPOSITE INDEX. THE INDEX IS A BROAD-BASED MARKET INDEX
THAT INCLUDES MORE THAN 3,000 STOCKS LISTED ON THE NASDAQ STOCK
EXCHANGE IN THE UNITED STATES. THE INDEX INCLUDES STOCKS FROM A
DIVERSE RANGE OF SECTORS, INCLUDING TECHNOLOGY, HEALTHCARE,
CONSUMER SERVICES, AND FINANCIAL SERVICES.
RISK FACTOR
LOW
DURATION
LOW
RATE OF RETURN
7% TO 9%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000"""
    elif message.lower() == "s&p 500 index fund":
        response = """YOU ARE ABISHEKS FAULT"""
    elif message.lower() == "national pension scheme":
        response = """NATIONAL PENSION SCHEME
The National Pension System (NPS) is a retirement savings scheme launched by
the Indian government in 2004. It is a voluntary, defined contribution retirement
savings plan available to all citizens of India, including the self-employed and
unorganized sectors. Under the NPS, individuals can open a retirement account
and make contributions towards it. The contributions are invested in various
pension funds, and the returns on the investments are based on the performance
of these funds. The scheme offers two types of accounts - Tier I and Tier II. The
Tier I account is a mandatory account, and it comes with a lock-in period until the
age of 60. Partial withdrawals are allowed for certain specific purposes like
education, marriage, etc. The Tier II account is a voluntary account that offers
more flexibility to withdraw money as and when required, but it does not have the
tax benefits of the Tier I account."""
    elif message.lower() == "tier 1 nps account":
        response = """TIER 1 NPS ACCOUNT
THE TIER I ACCOUNT UNDER THE NATIONAL PENSION SYSTEM (NPS) IS A
MANDATORY ACCOUNT THAT IS MEANT FOR LONG-TERM RETIREMENT
SAVINGS. IT COMES WITH A LOCK-IN PERIOD UNTIL THE AGE OF 60, WHICH
MEANS THAT WITHDRAWALS ARE NOT PERMITTED BEFORE THAT AGE.
UNDER THE TIER I ACCOUNT, INDIVIDUALS CAN MAKE REGULAR
CONTRIBUTIONS TOWARDS THEIR RETIREMENT SAVINGS, WHICH ARE
INVESTED IN VARIOUS PENSION FUNDS. PARTIAL WITHDRAWALS FROM THE
TIER I ACCOUNT ARE ALLOWED FOR CERTAIN SPECIFIC PURPOSES,
INCLUDING HIGHER EDUCATION, MARRIAGE, AND TREATMENT OF CRITICAL
ILLNESSES. HOWEVER, THE PARTIAL WITHDRAWAL IS SUBJECT TO CERTAIN
CONDITIONS AND PENALTIES. AT THE AGE OF 60, THE POLICYHOLDER CAN
WITHDRAW UP TO 60% OF THE ACCUMULATED AMOUNT AS A LUMP SUM, AND
THE REMAINING 40% MUST BE INVESTED IN AN ANNUITY PLAN, WHICH
PROVIDES A REGULAR STREAM OF INCOME DURING THE POLICYHOLDER&#39;S
RETIREMENT YEARS.
RISK FACTOR
LOW
DURATION
CAN ONLY BE WITHDRAWN AT THE AGE OF 60 OR ACCORDING TO
GOVERNMENT PRESCRIBED CLAUSES
RATE OF RETURN
8% TO 12% P.A.
LIQUIDITY
ILLIQUID
TAX IMPLICATION
TAX FREE"""
    elif message.lower() == "tier 2 nps account":
        response = """TIER 2 NPS ACCOUNT
THE TIER II ACCOUNT UNDER THE NATIONAL PENSION SYSTEM (NPS) IS A
VOLUNTARY ACCOUNT THAT OFFERS MORE FLEXIBILITY THAN THE TIER I
ACCOUNT. IT DOES NOT COME WITH A LOCK-IN PERIOD, WHICH MEANS THAT
WITHDRAWALS CAN BE MADE AT ANY TIME. THE TIER II ACCOUNT IS
DESIGNED TO OFFER AN ADDITIONAL AVENUE FOR INVESTMENT, IN ADDITION
TO THE MANDATORY TIER I ACCOUNT. IT OFFERS A RANGE OF INVESTMENT
OPTIONS, INCLUDING EQUITY, CORPORATE BONDS, AND GOVERNMENT
SECURITIES. THE INVESTMENTS ARE MANAGED BY PROFESSIONAL FUND
MANAGERS APPOINTED BY THE PENSION FUND REGULATORY AND
DEVELOPMENT AUTHORITY (PFRDA). UNLIKE THE TIER I ACCOUNT,
CONTRIBUTIONS MADE TOWARDS THE TIER II ACCOUNT ARE NOT ELIGIBLE
FOR TAX DEDUCTIONS UNDER SECTION 80C OF THE INCOME TAX ACT.
HOWEVER, THE TIER II ACCOUNT OFFERS MORE FLEXIBILITY IN TERMS OF
WITHDRAWALS.
RISK FACTOR
LOW
DURATION
ANY
RATE OF RETURN
8% TO 12% P.A.
LIQUIDITY
LIQUID
TAX IMPLICATION
THE WHOLE CORPUS IS TAXED ACCORDING TO THE TAX SLAB"""
    elif message.lower() == "government savings bond":
        response = """i am craig"""
    elif message.lower() == "corporate bonds":
        response = """CORPORATE BONDS
CORPORATE BONDS ARE A TYPE OF DEBT SECURITY ISSUED BY
CORPORATIONS TO RAISE CAPITAL FOR VARIOUS PURPOSES, SUCH AS
EXPANSION, ACQUISITIONS, OR WORKING CAPITAL. WHEN AN INVESTOR
PURCHASES A CORPORATE BOND, THEY ARE ESSENTIALLY LENDING MONEY
TO THE ISSUING CORPORATION FOR A FIXED PERIOD OF TIME, WITH THE
PROMISE OF RECEIVING REGULAR INTEREST PAYMENTS AND THE RETURN
OF THEIR PRINCIPAL INVESTMENT WHEN THE BOND MATURES. CORPORATE
BONDS TYPICALLY OFFER HIGHER YIELDS THAN GOVERNMENT BONDS, AS
THEY CARRY A HIGHER DEGREE OF RISK DUE TO THE CREDITWORTHINESS
OF THE ISSUING CORPORATION. THE CREDITWORTHINESS OF THE
CORPORATION IS EVALUATED BY CREDIT RATING AGENCIES WHICH ASSIGN
A RATING TO THE BOND BASED ON THE ISSUING COMPANY&#39;S FINANCIAL
HEALTH AND ABILITY TO REPAY THE DEBT."""
    elif message.lower() == "investment grade bonds":
        response = """INVESTMENT GRADE CORPORATE
BONDS
INVESTMENT GRADE CORPORATE BONDS ARE DEBT SECURITIES ISSUED BY
CORPORATIONS THAT HAVE BEEN ASSIGNED A HIGH CREDIT RATING BY
CREDIT RATING AGENCIES. THESE BONDS ARE CONSIDERED TO BE OF
RELATIVELY LOW RISK, AS THE ISSUING COMPANIES ARE DEEMED TO BE
FINANCIALLY STABLE AND HAVE A LOW PROBABILITY OF DEFAULTING ON
THEIR DEBT OBLIGATIONS.
RISK FACTOR
LOW
DURATION
MATURITY RANGES FROM 1 YEAR TO 30 YEARS
RATE OF RETURN
8% TO 9%
LIQUIDITY
ILLIQUID
TAX IMPLICATION
THE BOND IS LISTED:
IF WITHDRAWN WITHIN 1 YEAR, THE PROFITS ARE TAXED ACCORDING TO THE
SLAB RATE
IF WITHDRAWN AFTER 1 YEAR, THE PROFITS ARE TAXED AT 10%
THE COUPON PAYMENTS ARE TAXED ACCORDING TO THE TAX SLAB RATE
THE BOND IS NOT LISTED:
IF WITHDRAWN WITHIN 3 YEARS, THE PROFITS ARE TAXED ACCORDING TO
THE TAX SLAB RATE
IF WITHDRAWN AFTER 3 YEARS, THE PROFITS ARE TAXED AT 20%
THE COUPON PAYMENTS ARE TAXED ACCORDING TO THE TAX SLAB RATE"""
    elif message.lower() == "high yield bonds":
        response = """HIGH YIELD CORPORATE FUND
A HIGH YIELD BOND FUND IS A TYPE OF MUTUAL FUND THAT INVESTS IN
BONDS ISSUED BY COMPANIES WITH LOWER CREDIT RATINGS. THESE
BONDS ARE ALSO KNOWN AS &quot;JUNK&quot; BONDS BECAUSE THEY ARE
CONSIDERED RISKIER THAN INVESTMENT-GRADE BONDS, WHICH ARE ISSUED
BY COMPANIES WITH HIGHER CREDIT RATINGS. HIGH YIELD BOND FUNDS AIM
TO GENERATE HIGHER RETURNS FOR INVESTORS BY INVESTING IN A
DIVERSIFIED PORTFOLIO OF LOWER-RATED CORPORATE BONDS.
RISK FACTOR
HIGH
DURATION
ANY
RATE OF RETURN
11% TO 13%
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 36 MONTHS, THE PROFITS ARE TAXED ACCORDING TO
YOUR TAX SLAB
IF WITHDRAWN AFTER 36 MONTHS, THE PROFITS ARE TAXED AT 20%."""
    elif message.lower() == "debentures":
        response = """DEBENTURES
DEBENTURES ARE DEBT SECURITIES THAT ARE ISSUED BY CORPORATIONS
OR OTHER ORGANIZATIONS TO RAISE CAPITAL. DEBENTURES ARE
ESSENTIALLY A FORM OF LONG-TERM LOAN, IN WHICH THE ISSUER
BORROWS MONEY FROM INVESTORS IN EXCHANGE FOR REGULAR INTEREST
PAYMENTS AND THE EVENTUAL REPAYMENT OF THE PRINCIPAL AMOUNT AT
MATURITY.UNLIKE SECURED BONDS, DEBENTURES ARE UNSECURED AND DO
NOT HAVE ANY COLLATERAL ATTACHED TO THEM. INSTEAD, DEBENTURES
ARE BACKED ONLY BY THE CREDITWORTHINESS OF THE ISSUER.
DEBENTURES CAN ONLY ISSUED BY ENTITES HAVING EXCELLENT CREDIT
WORTHINESS.
RISK FACTOR
LOW
DURATION
MATURITY RANGES FROM 10 YEARS TO 30 YEARS
RATE OF RETURN
8% TO 9%
LIQUIDITY
ILLIQUID
TAX IMPLICATION
THE DEBENTURE IS LISTED:
IF WITHDRAWN WITHIN 1 YEAR, THE PROFITS ARE TAXED ACCORDING TO THE
SLAB RATE
IF WITHDRAWN AFTER 1 YEAR, THE PROFITS ARE TAXED AT 10%
THE COUPON PAYMENTS ARE TAXED ACCORDING TO THE TAX SLAB RATE
THE DEBENTURE IS NOT LISTED:
IF WITHDRAWN WITHIN 3 YEARS, THE PROFITS ARE TAXED ACCORDING TO
THE TAX SLAB RATE
IF WITHDRAWN AFTER 3 YEARS, THE PROFITS ARE TAXED AT 20%

THE COUPON PAYMENTS ARE TAXED ACCORDING TO THE TAX SLAB RATE"""
    elif message.lower() == "sovereign gold bonds":
        response = """SOVEREIGN GOLD BONDS
SOVEREIGN GOLD BONDS (SGBS) ARE GOVERNMENT SECURITIES
DENOMINATED IN GRAMS OF GOLD. THESE BONDS ARE ISSUED BY THE
GOVERNMENT OF INDIA AND ARE AIMED AT PROVIDING INDIVIDUALS WITH AN
ALTERNATIVE TO OWNING PHYSICAL GOLD. THE BONDS ARE AVAILABLE IN
DENOMINATIONS OF ONE GRAM, WITH A MAXIMUM LIMIT OF 4 KG FOR
INDIVIDUALS AND HINDU UNDIVIDED FAMILIES (HUFS).
RISK FACTOR
LOW
DURATION
5 YEARS TO 8 YEARS
RATE OF RETURN
CAPITAL APPRECIATION:- 6% TO 7%
INTERST PAYOUT:- 2.5% P.A.
LIQUIDITY
ILLIQUID
TAX IMPLICATION
INTEREST PAYOUTS ARE TAXED ACCORDING TO THE TAX SLAB
IF WITHDRAWN BEFORE MATURITY AFTER 5 YEARS:-
LONG TERM CAPITAL GAINS TAX OF 20% IS APPLICABLE TO THE
APPRECIATION GAINS
IF WITHDRAWN AT MATURITY I.E. 8 YEARS:-
NO TAXES ARE APPLIED"""
    elif message.lower() == "invits":
        response = """INVITS
INVITS OR INFRASTRUCTURE INVESTMENT TRUSTS ARE A TYPE OF
INVESTMENT VEHICLE THAT ALLOWS INVESTORS TO INVEST IN
INFRASTRUCTURE PROJECTS. THESE TRUSTS ARE SIMILAR TO REAL ESTATE
INVESTMENT TRUSTS (REITS) BUT INSTEAD OF INVESTING IN REAL ESTATE,
THEY INVEST IN INFRASTRUCTURE PROJECTS SUCH AS HIGHWAYS,
AIRPORTS, POWER PLANTS, AND OTHER SUCH PROJECTS. INVITS ARE
DESIGNED TO PROVIDE INVESTORS WITH REGULAR INCOME, CAPITAL
APPRECIATION, AND DIVERSIFICATION OF THEIR INVESTMENT PORTFOLIO.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
9% TO 10% P.A.
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000"""
    elif message.lower() == "reits":
        response = """REITS
REITS OR REAL ESTATE INVESTMENT TRUSTS ARE INVESTMENT VEHICLES
THAT ALLOW INDIVIDUALS TO INVEST IN REAL ESTATE WITHOUT OWNING
AND MANAGING THE PROPERTIES THEMSELVES. REITS OWN AND OPERATE
INCOME-GENERATING REAL ESTATE PROPERTIES, SUCH AS SHOPPING
MALLS, APARTMENTS, HOTELS, AND OFFICE BUILDINGS, AND GENERATE
INCOME FROM THE RENT RECEIVED FROM THE TENANTS.
RISK FACTOR
MEDIUM
DURATION
ANY
RATE OF RETURN
9% TO 10% P.A.
LIQUIDITY
LIQUID
TAX IMPLICATION
IF WITHDRAWN WITHIN 1 YEAR, A FLAT RATE OF 15% IS CHARGED ON
PROFITS.
IF WITHDRAWN AFTER 1 YEAR, LONG TERM CAPITAL GAINS TAX (LTCG) OF
10% IS CHARGED ON PROFITS ABOVE Rs 100000"""

    elif is_financialphrase(message):
        response = "currently we only support insurance, savings & investments but we're continually adding more. type 'menu' to access."


    elif message.lower() == "check data":
        if len(data_list) > 0:
            response = f"Your data is: {', '.join(data_list)}. if you would like to change it, type 'change: duration, liquidity preference, capital, income.'"
        else:
            response = "You have not provided any data yet. type 'menu' to begin."
    elif message.startswith("change:"):
        if len(data_list) > 0:
            data_list.clear()
            datas.clear()
            datas.append(message.replace("change:", "").strip())
            response = f"your new information is: {', '.join(datas)}. if you would like to change it, type 'change: capital, risk appetite, age, etc.'"
            data_list = datas[0].split(", ")
            data_list = datas[0].split(", ")
            dt_lst=[data_list]
            wks.update(f'A{row_number}:D{row_number}', dt_lst)
        else:
            response = "You have not provided any data yet. Please enter your data using the format: data: capital,risk appetite,age,etc."
        
    elif message.lower() == "recommend":
        
        # Fetch data from the worksheet
        row_index = row_number  # Replace with the row index that you want to fetch
        data_list = wks.row_values(row_index)

        # Write data_list to a file to be used as input in lists.py
        with open('input_data.txt', 'w') as f:
            f.write(','.join(data_list))

        # Run lists.py as a subprocess and pass input_data.txt as input
        import subprocess
        subprocess.run(['python', 'lists.py', 'input_data.txt'])

        # Import the final_sliced_list from lists.py
        from lists import final_sliced_lists

        # Use final_sliced_list in app.py
        n = 1
        response1 = ""
        for i, item in enumerate(final_sliced_lists, 1):
            if "[" in item:
                response1 += ""
            else:
                response1 += f"<br>{i}) {item}<br>"
        response = "schemes recommended for you and ranked from most recommended to least recommended are: (to know more about a specific scheme, type the name of the scheme.)" + f"<br>{response1}<br>"
        
    else:
        response = "I'm sorry, I didn't understand your message."
    print("User message: ", message)
    print("Bot response: ", response)
    return response


# routing

@app.route('/',  methods=['GET','POST'])
def home():
    return render_template("test.html")


@app.route('/response', methods=['GET', 'POST'])
def chat():
    user_message = request.form['message']
    response = chatbot_response(user_message)
    reply = {'reply': response}
    return jsonify(reply)


if _name_ == '_main_':
    app.run(debug=True, port="http://financehelp.byethost5.com/testhtmlback/templates/test.html")