# Original Lists
financialphrases = ['yield', 'net worth', 'options', 'mutual fund', 'inflation', 'savings', 'blue chip', 'risk management', 'credit rating', 'hedge fund', 'bond', 'stock market', 'cash flow', 'equity', 'bear market', 'venture capital', 'accounting', 'bankruptcy', 'diversification', 'passive income', 'stock exchange', 'taxes', 'retirement planning', 'liquidity', 'capital gains', 'financial advisor', 'investment portfolio', 'asset allocation', 'credit score', 'retirement savings', '529 plan', 'emergency fund', 'student loans', 'mortgage', 'interest rate', 'IRA', '401(k)', 'stock options', 'dividend', 'capital loss', 'real estate investing', 'term life insurance', 'whole life insurance', '401(k) rollover', 'annuity', 'commodity trading', 'forex trading', 'robo-advisor', 'cryptocurrency', 'initial public offering (IPO)', 'diversified portfolio', 'estate planning', 'tax planning', 'wealth management', 'financial literacy', 'financial goals', 'passive investing', 'active investing', 'dollar-cost averaging', 'financial independence', 'early retirement', '529 college savings plan', '529 prepaid tuition plan', 'individual brokerage account', 'joint brokerage account', 'health savings account (HSA)', 'certificate of deposit (CD)', 'money market account', 'credit card debt', 'rental property investing', 'socially responsible investing', 'business loans', 'angel investing', 'venture debt', 'capital market', 'market volatility', 'market correction', 'market trend', 'market capitalization', 'fundamental analysis', 'technical analysis', 'portfolio rebalancing', 'capital preservation', 'risk tolerance', 'dividend reinvestment plan (DRIP)']


first_elements_list = ["recurring deposits", "fixed deposits", "saving accounts", "national saving certificates", "sukanya samridhi yojana", "provident fund", "money market funds", "corporate bond fund", "government bond fund", "mixed bond fund", "high yield bond funds", "bluechip equity funds", "large cap equity fund", "small cap equity fund", "mid-cap equity fund", "equity oriented hybrid funds", "debt oriented hybrid funds", "nifty 50 index funds", "sensex index fund", "nifty next 50 index funds", "nasdaq composite index funds", "s&p 500 index fund", "tier 1 nps account", "tier 2 nps account", "government saving bond", "investment grade corporate bonds", "high yield bonds", "debentures", "invits", "reits"]

# Checking for common words
common_words = set(financialphrases) & set(first_elements_list)

# Creating new version of financialphrases list with common words removed
financialphrases_new = list(set(financialphrases) - common_words)
print(financialphrases_new)
